### ISSUE TITLE
Tensorflow model 

### ISSUE THREAD

**Issue by lfoppiano** [M3RG-IITD/MatSciBERT#1]
I was wondering whether you could also release the converted model to TF in the huggingface repository? 
Thank you in advance

**Comment by vipulg13** [comment]
@lfoppiano, are you planning to support this into GROBID-Quantities?

**Comment by lfoppiano** [comment]
The new [DeLFT](https://github.com/kermitt2/delft) version supports feeding models directly from hugginface, so no need anymore for this 😄

**Comment by vipulg13** [comment]
Dear @lfoppiano, after commenting here, I happened to check the DeLFT documentation and huggingface MATPUSciBERT model, and got an answer to my question. That's why, I deleted the comment. Nevertheless, thanks for your prompt reply. Cheers!
