### ISSUE TITLE
where can i find a config.json to use the ner models ?

### ISSUE THREAD

**Issue by naohri** [M3RG-IITD/MatSciBERT#10]

**Comment by zakidotai** [comment]
Hi @naohri ,

We do not have it for ner models.

You can download the trained NER models from [Zenodo](https://doi.org/10.5281/zenodo.6413296) and refer to the following [notebook](https://github.com/M3RG-IITD/MatSciBERT/blob/main/ner/ner_inference.ipynb) to use the NER model.

**Comment by zakidotai** [comment]
You can reopen the issue in case you have follow up queries. Thanks!
