### ISSUE TITLE
Finetune MatSciBERT for Classification Task

### ISSUE THREAD

**Issue by kdmsit** [M3RG-IITD/MatSciBERT#3]
Hello,

We want to perform some classification tasks, based on some textual description obtained for the materials domain. We want to fine-tune MatSCiBERT further on our task. How to do that? is there any notebook for that?

**Comment by zakidotai** [comment]
Hi, You can use the **cls.py** script present in the **cls** folder. For fine-tuning on the custom dataset, you can add new files in the **dataset** folder inside **cls** and then provide its path in **cls.py**.
