### ISSUE TITLE
Problems with NER inference in the provided notebook

### ISSUE THREAD

**Issue by mamebios** [M3RG-IITD/MatSciBERT#4]
Hello, I've encountered a problem while running the notebook you've provided for NER inference. It happens in the `trainer.predict(caption_dataset)` step, and from my understanding it's occurring because the forward method of the CRF model, from the torchcrf lib, does not implement an argument for the input_ids, attention_mask, token_type_ids and labels from the `caption_dataset`, and so the trainer just ignores these fields, making the error occur. 

Here follows the error:
```PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
***** Running Prediction *****
  Num examples = 5
  Batch size = 64
The following columns in the test set don't have a corresponding argument in `BERT_CRF.forward` and have been ignored: input_ids, attention_mask, token_type_ids, labels. If input_ids, attention_mask, token_type_ids, labels are not expected by `BERT_CRF.forward`,  you can safely ignore this message.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-44-e3bf822ca727>](https://localhost:8080/#) in <module>
     12 )
     13 
---> 14 preds = np.argmax(trainer.predict(caption_dataset).predictions, axis=2)
     15 
     16 true_preds = [

7 frames
[/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py](https://localhost:8080/#) in pad(self, encoded_inputs, padding, max_length, pad_to_multiple_of, return_attention_mask, return_tensors, verbose)
   2937         # The model's main input name, usually `input_ids`, has be passed for padding
   2938         if self.model_input_names[0] not in encoded_inputs:
-> 2939             raise ValueError(
   2940                 "You should supply an encoding or a list of encodings to this method "
   2941                 f"that includes {self.model_input_names[0]}, but you provided {list(encoded_inputs.keys())}"

ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided []
```

As the torchcrf lib is not specified, I've attempted to use this one: [pytorch-crf](https://github.com/kmkurn/pytorch-crf#egg=pytorch_crf), and I think this is the cause of the problem as this CRF model forward method doesn't provide arguments for said dataset columns, so having the right lib specified would help a lot.

Also I've seem that you are using the chemdataextractor v1, wich the creators apparently stopped suport in favor of the chemdataextractor v2. This makes it impossible for the Paragraph() method to download a required model to work. But I've found that switching to v2 with `!pip install chemdataextractor2` and `from chemdataextractor.doc.text import Paragraph` works just fine.

**Comment by zakidotai** [comment]
@mamebios All the libraries with respective versions are mentioned in the requirements.txt file in the main folder of the [repository](https://github.com/M3RG-IITD/MatSciBERT). If you are still getting the error, check the list of sentences that you are using as input. If you still get the error, fork this repository, push your notebook in the forked version, and share it's link here. We will be glad to help.

With respect to chemdataextractor, if you want to use the v1, you can follow the steps listed in its [official documentation](http://chemdataextractor.org/docs/install).

Thanks for sharing the info about cde v2!

**Comment by mamebios** [comment]
Thanks for the answer! Adjusted for the requirements and it worked! 

Now I'm going to try to do inference with the relation extraction model as well.
