### ISSUE TITLE
Inference with the Relation Classification model

### ISSUE THREAD

**Issue by mamebios** [M3RG-IITD/MatSciBERT#5]
Hello, currently I'm trying to adapt the notebook you've provided to make inference with the RC model. My issue so far is to determine what to consider as labels to the text I want to make inference on. Should I just consider a random label for the inference dataset, and the trainer will take care of the rest?

**Comment by zakidotai** [comment]
Hello, you can use the [relation_classification.py](https://github.com/M3RG-IITD/MatSciBERT/blob/main/relation_classification/relation_classification.py) script and use only the trainer.evaluate() part. I hope you have the finetuned model for this case. Providing a random label should work.

**Comment by mamebios** [comment]
Thanks! I've managed to make it work for inference. In my case I've acquired the predictions with `trainer.predict(dataset).predictions`, and the associated label with `id2tag[np.argmax(prediction)]`.
