### ISSUE TITLE
About continue pretraining datasets

### ISSUE THREAD

**Issue by tszslovewanpu** [M3RG-IITD/MatSciBERT#7]
hello~ how to get the 150 K paper limited to 4 Material Science families, is it the only way that i have to collect the papers manually and parsing these documents?

**Comment by zakidotai** [comment]
> hello~ how to get the 150 K paper limited to 4 Material Science families, is it the only way that i have to collect the papers manually and parsing these documents?

Hi,
The procedure to create dataset is described in 
1. https://www.sciencedirect.com/science/article/pii/S2666389921001239
2. [MatSciBERT paper](https://www.nature.com/articles/s41524-022-00784-w)
