### ISSUE TITLE
NER Procedure

### ISSUE THREAD

**Issue by YikunHan42** [M3RG-IITD/MatSciBERT#9]
Hello,

I would like to ask what the steps of this NER are. I see a total of four `run.sh` under the NER path and under the model path. Do I need to run all these script files? Do all these scripts need to be run? If so, what is the order of precedence? What about the `ner_inference.ipynb` file?

Thanks for the wonderful work you have done before, and I hope to get answers.

**Comment by YikunHan42** [comment]
```python
ner_model_path = os.path.join(os.getcwd(), 'models/matscholar')
model.load_state_dict(torch.load(os.path.join(ner_model_path, 'pytorch_model.bin'), map_location='cpu'))
model = model.to(device)
```
If understood correctly, it should be necessary to get the trained NER model. Is it necessary to execute specific bash file to generate `pytorch_model.bin`?

**Comment by zakidotai** [comment]
> Hello,
> 
> I would like to ask what the steps of this NER are. I see a total of four `run.sh` under the NER path and under the model path. Do I need to run all these script files? Do all these scripts need to be run? If so, what is the order of precedence? What about the `ner_inference.ipynb` file?
> 
> Thanks for the wonderful work you have done before, and I hope to get answers.

Hi @YikunHan42 

The run.sh  file in specific folder generate only one model which is the best one. The run.sh file in the ner directory can  be used to generate models for all datasets, all the folds, for all the seeds.

The ner_inference.ipynb file is provided so that one can extract  NERs  from their own text.

I hope this helps.

**Comment by zakidotai** [comment]
> ```python
> ner_model_path = os.path.join(os.getcwd(), 'models/matscholar')
> model.load_state_dict(torch.load(os.path.join(ner_model_path, 'pytorch_model.bin'), map_location='cpu'))
> model = model.to(device)
> ```
> 
> If understood correctly, it should be necessary to get the trained NER model. Is it necessary to execute specific bash file to generate `pytorch_model.bin`?

You can download the trained model from the [Zenodo repository of MatSciBERT](https://doi.org/10.5281/zenodo.6413296)

OR

You can it yourself using the run.sh scripts in specific folders.

**Comment by YikunHan42** [comment]
> > ```python
> > ner_model_path = os.path.join(os.getcwd(), 'models/matscholar')
> > model.load_state_dict(torch.load(os.path.join(ner_model_path, 'pytorch_model.bin'), map_location='cpu'))
> > model = model.to(device)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If understood correctly, it should be necessary to get the trained NER model. Is it necessary to execute specific bash file to generate `pytorch_model.bin`?
> 
> You can download the trained model from the [Zenodo repository of MatSciBERT](https://doi.org/10.5281/zenodo.6413296)
> 
> OR
> 
> You can it yourself using the run.sh scripts in specific folders.

Thank you very much for your reply. One more question is: if I use this trained model, can I still run `ner_inference.ipynb`?

I tried the following steps:
1. uploaded the https://huggingface.co/m3rg-iitd/matscibert and Zenodo repo together to a linux server and executed the `install.requirements.sh` script
2. changed the path to the code in `ner_inference.ipynb` to local, and also changed `ner.dataset.py`, e.g., pasted the code from Github.

```python
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, inp, labels).
        self.inp = inp
        self.labels = labels

    def __getitem__(self, idx): item = {key: torch.
        item = {key: torch.tensor(val[idx]) for key, val in self.inp.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self).
        return len(self.labels)
```

![image](https://github.com/M3RG-IITD/MatSciBERT/assets/101811299/98d1279a-5ec2-45d7-a654-33c21b730eb1)

Am I overlooking some pre-steps?

**Comment by YikunHan42** [comment]
I tried this `ner_inference.ipynb` step by step, and now I don't know how to fix it. It seems that retraining `bash.sh` in `matscholar` doesn't work either

![image](https://github.com/M3RG-IITD/MatSciBERT/assets/101811299/9f23355f-5bfc-4cee-b131-8d2fa231298b)

**Comment by zakidotai** [comment]
> > > ```python
> > > ner_model_path = os.path.join(os.getcwd(), 'models/matscholar')
> > > model.load_state_dict(torch.load(os.path.join(ner_model_path, 'pytorch_model.bin'), map_location='cpu'))
> > > model = model.to(device)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If understood correctly, it should be necessary to get the trained NER model. Is it necessary to execute specific bash file to generate `pytorch_model.bin`?
> > 
> > 
> > You can download the trained model from the [Zenodo repository of MatSciBERT](https://doi.org/10.5281/zenodo.6413296)
> > OR
> > You can it yourself using the run.sh scripts in specific folders.
> 
> Thank you very much for your reply. One more question is: if I use this trained model, can I still run `ner_inference.ipynb`?
> 
> I tried the following steps:
> 
> 1. uploaded the https://huggingface.co/m3rg-iitd/matscibert and Zenodo repo together to a linux server and executed the `install.requirements.sh` script
> 2. changed the path to the code in `ner_inference.ipynb` to local, and also changed `ner.dataset.py`, e.g., pasted the code from Github.
> 
> ```python
> class MyDataset(torch.utils.data.Dataset):
>     def __init__(self, inp, labels).
>         self.inp = inp
>         self.labels = labels
> 
>     def __getitem__(self, idx): item = {key: torch.
>         item = {key: torch.tensor(val[idx]) for key, val in self.inp.items()}
>         item['labels'] = torch.tensor(self.labels[idx])
>         return item
> 
>     def __len__(self).
>         return len(self.labels)
> ```
> 
> ![image](https://user-images.githubusercontent.com/101811299/279868658-98d1279a-5ec2-45d7-a654-33c21b730eb1.png)
> 
> Am I overlooking some pre-steps?

It seems you are using a newer version of transformers. I checked with version 4.32.1, it is giving same  error. However, with the version specified in requirements.txt, it works fine.

**Comment by YikunHan42** [comment]
Thank you very much, I will retry as you said
